sudo: no

language: python

python:
  - 3.5

os:
  - linux

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt -r build-requirements.txt
  - pip install coveralls

script:
  - py.test --cov aiohttp_rest tests

after_success:
  - coveralls
