sudo: no

matrix:
    include:
        - os: linux
          python: 3.5
        - os: osx
          language: generic

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
  - $HOME/.cache/pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3.5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3.5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt -r build-requirements.txt

script:
  - py.test tests
