sudo: no

language: python

python:
  - 3.5

os:
  - linux
  - osx

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install -r build-requirements.txt

script:
  - py.test tests
